### ISSUE TITLE
Fuzzy search issue

### ISSUE THREAD

**Issue by soheilpro** [krisk/Fuse#106]
Hi,

What settings do I need to make 'omw' match 'Old Man's War' in this sample?

```
var books = [
  {
    'title': "Old Man's War"
  },
  {
    'title': 'The Lock Artist'
  }
];

var options = {
  keys: ['title']
};

var fuse = new Fuse(books, options);

var result = fuse.search('omw');
```

**Comment by cjackson234** [comment]
Looking at the documentation you can't really do that. Matching on abbreviation can be a bit messy, since the algorithms used here will also do a fuzzy match on the new abbrivations.

what I would do is pre-process the list you're searching.

```
var str     = "Old Man's War";
var matches = str.replace('\'','').match(/\b(\w)/g);              // ['O','M','W']
var acronym = matches.join(''); // OMW
```
  
Use the above and loop through the list and add the property acronym 

```
var books = [
  {
    'title': "Old Man's War"
    'acronym':"OMW"
  },
  {
    'title': 'The Lock Artist'
    'acronym': "TLA"
  }
];

var options = {
  keys: ['title','acronym ']
};

var fuse = new Fuse(books, options);

var result = fuse.search('omw');`
```

**Comment by peterbe** [comment]
This is the same fuzzy searching that GitHub and Atom uses. "Old Man's War" should match "omw" not because it's an abbreviation but because it contains "o" and "m" and "w" (case-insensitive) AND the order of "o" is before "m" is before "w".

I'd love to have that kind of matching. It's not very useful for English full-text searching but great for matching names.

**Comment by ianwitherow** [comment]
@peterbe Look at https://github.com/atom/fuzzaldrin or https://github.com/jeancroy/fuzzaldrin-plus - they work this way.

**Comment by peterbe** [comment]
Cool! That's what it's called. That's what I was trying to help explain here (except knowing the name). I think that's what this Issue is about.
