### ISSUE TITLE
search() returns T[] instead of FuseResult<T>[]

### ISSUE THREAD

**Issue by mattmazzola** [krisk/Fuse#303]
Even when `includeMatches` is set to true in the options `search` still returns T[]

![image](https://user-images.githubusercontent.com/2856501/56161234-e4760000-5f7d-11e9-9bb7-1d753e307535.png)

Seems related to this issue: https://github.com/krisk/Fuse/issues/265

The definition here seems like it should work and I'm guess it did in the issue above but something is breaking the `extends` test in TS. Maybe I have to configure options a different way?
![image](https://user-images.githubusercontent.com/2856501/56161377-30c14000-5f7e-11e9-87e0-868d592a91b2.png)

Repro: https://github.com/mattmazzola/fuse-type-bug

**Comment by marines** [comment]
Try passing the options as an argument without the intermediate `fuseOptions` variable. It worked for me. It's a bug nonetheless IMO.

**Comment by konjac-potage** [comment]
This is because type information is lost when casting into `Fuse.FuseOptions<IOption>`

Return type of `search()` is decided by the **type of** arguments passed to the `constructor` (that is denoted by `O` in definition).

Type `O = Fuse.FuseOptions<IOption> = {...., includeMatches?: boolean, ....}` does not extend `{ includeMatches: true }` and so `search()` returns `IOption[]`.

Pass options as object literal
```ts
const fuse = new Fuse(options, {
    ...
    includeMatches: true,
    ...
});
```

or fix type by using `as` (to prevent `ture` from being casted into `boolean`)
```ts
const fuseOptions = {
    ...
    includeMatches: true as true,
    ...
}
const fuse = new Fuse(options, fuseOptions);
```
