### ISSUE TITLE
Un-minified version in distribution

### ISSUE THREAD

**Issue by obihill** [krisk/Fuse#346]
Thanks for building this great plugin.

In your `dist` folder, could you please offer both a minified and un-minified version as is customary?

**Comment by cshoredaniel** [comment]
@krisk I've got a raw (= unminified) webpack generation in my tree.  I'd be happy to do the config for generating both on 'build' if you wish. I hadn't planned on submitting until I saw this issue because I assumed there was a reason you weren't doing this, and didn't want it.

**Comment by cshoredaniel** [comment]
@obihill  I wonder if you could take a look at https://github.com/krisk/Fuse/pull/365 and comment and/or test?

**Comment by obihill** [comment]
@cshoredaniel I took a look and I couldn't quite figure out the gist of the thread relative to this issue. Could you assist?

**Comment by cshoredaniel** [comment]
On 2020-03-23 3:09 p.m., Obinwanne Hill wrote:
>
> @cshoredaniel <https://github.com/cshoredaniel> I took a look and I 
> couldn't quite figure out the gist of the thread relative to this 
> issue. Could you assist?
>
>
Sorry for that.  Basically #262 was requesting ES6 modules but webpack 
(the bundler that was used by Fuse.js before the just pushed beta) can't 
create them so the bundler has been switched to Rollup, and a wider 
variety of outputs is now created via #367.

I was hoping you could add your thoughts as well as verify that there is 
no regression with respect to ES5 / UMD bundles.  The README in the new 
beta explains which each fuse.xxx.js is for. Oh, and at the verify least 
you will need fuse.js instead of fuse.raw.js for the unminified version 
as the naming scheme has been normalized.

**Comment by cshoredaniel** [comment]
@obihill not sure if you get notified of email replies, so just a quick mention to let you know I replied.

**Comment by obihill** [comment]
@cshoredaniel Yes, I received the notifications, but quite late so I left replying until now.

Thanks a lot for the clarification. I took a look at `fuse.js` and it looks like what I would expect i.e. the structure from a UMD standpoint. I won't be working on the webapp where I'm using this until later in the week, so I can't verify that it works. However, I really don't see why it wouldn't if it's `fuse.min.js` un-minified.

Thanks again for your assistance on this. Much appreciated.

**Comment by obihill** [comment]
@cshoredaniel Just wanted to update you. Everything's working great now. I tried with `fuse.js` of release version 5.1.0, and it passes muster. Thanks for the assistance.
