### ISSUE TITLE
Performance metrics

### ISSUE THREAD

**Issue by arkRedM** [krisk/Fuse#492]
Please include information regarding performance metrics(time and memory usage)
There are 2 metrics that help in some design decisions

1. Cost of instantiating(Time for instantiating - factors it depends on, Will deep nested structure take more time?)
2. Cost of search(How long to fuzzy search? Does the structure of doc(search item) affect performance?)

**Comment by krisk** [comment]
I've added a [performance guide](https://github.com/krisk/Fuse/blob/main/docs/performance.md) to the docs that covers what affects indexing and search speed. Real numbers vary too much across hardware, key count, and value length — any specific numbers I publish would be wrong for most people. That's why the guide includes a benchmark script you can run against your own data. Will be live on the docs site with the next update.
