### ISSUE TITLE
add advanced search logic

### ISSUE THREAD

**Issue by btm1** [krisk/Fuse#53]
This is almost so bad ass:

I'd like to do advanced searches like:

cats || dogs -> return any object containing cats or dogs in any value
cats && dogs -> return objects that have a value containing cats and dogs
name:rob && pet:dog -> return objects who's field "name" is equal to rob and who's field "pet" is equal to dog

**Comment by krisk** [comment]
Oh, that's quite the feature. This is probably a bit too much for the library itself to handle. Otherwise, it goes from being lightweight to heavyweight :) However, it's a great catalyst conversation for a plugin functionality I've been meaning to add to Fuse. 

Do you suppose this feature request is a good candidate for a Fuse.js plugin?

**Comment by janraasch** [comment]
Seems like this could be done by simply making two `Fuse#search`es and then takin the `union` or `intersection` of the result arrays. In that case it could simply be another `npm`  module which depends on this library.
