### ISSUE TITLE
export index

### ISSUE THREAD

**Issue by stefanocudini** [krisk/Fuse#55]
I want export fuzzy index with in an object  for next loading

Can you add a new method for this?

**Comment by s-panferov** [comment]
+1 to this. I'm building a doc generator with searching support and it will be very helpful to build search index in compile-time.

**Comment by jeancroy** [comment]
Fuse is an online search algorithm. It will loop over every character of every entry on every search. There is no preparation step of building a search index.

In general it is hard to do such a preparation step for fuzzy searching using edit distance. You basically have to pre-compute spelling error then put those errors in an exact search index. And it takes a tons of memory and some loading time hit. And to mitigate that it's customary to limit index to like 2 or 3 error in the words.

If you need somehting with a preparation phase you can look at fuzzyset.js. It use n-gram instead of edit distance.
