### ISSUE TITLE
it didn't suggest the best result

### ISSUE THREAD

**Issue by craigcosmo** [krisk/Fuse#569]
with a List like this
```js
const list = [
	{label:'exhibit motorcar engine v11'},
	{label:'exhibit motorcar engine v10'},
	{label:'exhibit motorcar engine v12'},
	{label:'selling motorcar engine fly over v15'}
]

const searchWord = 'engine v15'
const options = {
			isCaseSensitive: false,
			keys: ['label'],
		}
const fuse = new Fuse(list, options)
const result = fuse.search(searchWord)

console.log(result)

[
	{label:'exhibit motorcar engine v11'},
	{label:'exhibit motorcar engine v10'},
	{label:'exhibit motorcar engine v12'},
	{label:'selling motorcar engine fly over v15'}
]

```

What I got back is that exact order. Which is not correct, the item with keyword `engine` and `v15` should be on the top score. If search result consists of 100 item, the `selling motorcar engine fly over v15` will be about at the bottom of the result. Which is totally wrong. Because `selling motorcar engine fly over v15` is most relevant to search term `engine v15`.

 I was expecting the result below, which is more accurate.

```
[
        {label:'selling motorcar engine fly over v15'},
	{label:'exhibit motorcar engine v11'},
	{label:'exhibit motorcar engine v10'},
	{label:'exhibit motorcar engine v12'}	
]
```

**Comment by andyjp** [comment]
I was messing around with this on the demo page (https://fusejs.io/demo.html). The score is higher for the label with v15 so looks like you may just need to add a sort function like this:

![image](https://user-images.githubusercontent.com/8158746/135531158-6352699b-edb8-439c-a312-dedc8c08c2c9.png)

Looks like the docs say that it will sort by ascending relevance score (https://fusejs.io/api/options.html#sortfn). It would probably make more sense if the default was descending though.

**Comment by craigcosmo** [comment]
I tried the sort desc, with the `v15` key word, I still end up with the result that has key word `v15` lays in the middle of the score. while there is only one `v15` entry in a list of many entries.

this library wil proortize the `V1` in the oder of the appearance of the sentence.

fore xample: if there is 3 results, they will be ordered like this

`this is my v10` will appear last
`the only machine is v15` will appear middle
`the only machine v10' will appear first

Obviously the sentence with the word `v15` is the most relevant result is put in the middle.

**Comment by jrista** [comment]
Just to keep this from getting closed...I've been having a number of odd issues with Fuse like this. Where it will rank less relevant, and sometimes completely irrelevant, results higher than much more relevant results. If you are also restricting the search results with additional config, this often results in relevant results appearing and disappearing in the results as you continue to adjust your criteria (i.e. continue typing to add more characters). 

What is quite odd is that sometimes with a minimum 3-letter match, the three letters searched may not appear near each other in many of the results... It would seem those results should not appear, yet they do. 

I've been completely stumped by the problem, but it seems to largely be the same issue as this...rankings are not quite right, and the most relevant results are not always ranked highest.

**Comment by jrista** [comment]
As an example of the oddity I am seeing... With the following search, I would expect Certified Nurse Assistant to be a solid second at the very least...and if I type out `Nurse` specifically, then it should be #1, hands down given its an exact match. Nursing should be first or second, first initially given its an initial match closer to the beginning of the string.

As for the rest...I don't even know why any of the rest is even matching, and as I fiddle with threshold and distance, things just change in oddity, but don't really seem to actually get better:

<img width="1789" alt="Screen Shot 2021-11-01 at 10 58 23 AM" src="https://user-images.githubusercontent.com/238441/139908702-38c5c4c6-38a6-44ad-8a47-51b11b93db00.png">
<img width="1788" alt="Screen Shot 2021-11-01 at 10 58 38 AM" src="https://user-images.githubusercontent.com/238441/139908728-50330204-3e09-4dff-adbe-57d4aaee6a65.png">
<img width="1792" alt="Screen Shot 2021-11-01 at 10 58 55 AM" src="https://user-images.githubusercontent.com/238441/139908714-fa905ffc-6796-4639-94cd-0fe9581ffce6.png">

I am at a loss as to how to deal with this. This is the general behavior of our search with Fuse.js...its....it seems to have matching and ranking issues, and seems to spread its "fuzziness" over a FAR too broad net, often missing close or exact matches when it should, and if it captures them, it ranks them very low.

**Comment by jrista** [comment]
@krisk ^

**Comment by wilrevehl** [comment]
Hello and thank you for this module. It is sincerely appreciated. I wanted to chime in on this thread as it may be related to an issue we have been seeing. There appears to be a possible charset or key match discrepancy we have not been able to exactly pinpoint, but the theory has some evidence behind it. We have an array with the word INSTRUMENTATION in it but when you type Inst, it doesn't find it. However, if you type nstru without the I it does find it. There's no case sensitivity on or anything. I wish I could show you the app but we're on a strict NDA. Thanks for all you do.

**Comment by jrista** [comment]
@wilrevehl Thanks for the post. 

I wonder if that might explain some of the odd behavior we have been experiencing lately, that is very much the same. When we type in certain strings, sometimes Fuse will find...matches, sometimes it will suddenly stop matching anything, until we either add more to the search criteria, or remove something. 

It's been a very confusing problem, and we have been finding that more often than not, the results are only occasionally truly relevant, and usually ranked poorly, often ranked without any real relevance to the search criteria. 

I've had to shelve my research into the problem for now, as we have a lot of other features to implement. Sadly, no one, neither our client nor our team, are very happy with the results so far. Sadly, it doesn't seem like there are very many other fuzzy search options out there...the community sort of piled in on Fuse.js and other libs from years back have all gone stale.

**Comment by jrista** [comment]
I don't believe a fix has been found for this issue. Its a pretty major issue, as the majority of results end up being irrelevant given the current state of Fuse.js...

**Comment by zehawki** [comment]
This library does not produce expected results at all. Ive been trying various small datasets where I've been very puzzled by the results.

I've reduced it down to a small example tested on the live demo page which doesnt work:

```
[
  {
    "name": "Icon 1c",
    "desc": "Through contributions, donations, and sponsorship, you allow Fuse.js to thrive. Also, you will be recognized as a beacon of support to open-source developers.",
    "notes": "This is only for your reference, it will not display with the component."
  },
  {
    "name": "Icon 3",
    "desc": "The text is used to generate the slug. Note that if you change the slug, the URL of this page will change. Do not change the slug unless really needed."
  }
]
```

Default options and keys =

```
  keys: [
    "name",
    "desc",
    "notes"
  ]
```

Now a search for `URL`, `needed`, `unless`, `really needed`, `slug change`, `developers` and so on produces no results at all.
A search for `fuse` thrown up the 2nd record.

----------

I see other threads: https://github.com/krisk/Fuse/issues/562, https://github.com/krisk/Fuse/issues/544

----------

And we know we should stay away from a lib that resorts to a bot to force close issues.

**Comment by jrista** [comment]
This issue keeps getting closed because of the darn bot...but it is definitely not fixed. Is there a way to flag or label this bug so the bot won't keep closing it? Right now, Fuse.js does not really seem to work, and it desperately needs to be fixed.

I am also curious...is this project still being worked on? Or has Fuse.js been abandoned?

**Comment by zehawki** [comment]
I couldnt get Lunr to work either. Surprisingly all these libs are quite old. https://www.npmtrends.com/elasticlunr-vs-fuse.js-vs-fuzzy-vs-fuzzysearch-vs-lunr-vs-reds-vs-search-index

**Comment by krisk** [comment]
Ok, thank you for the info here. Let me debug and circle back here.

**Comment by krisk** [comment]
@zehawki I'm looking at the example you provided, this isn't a bug. 

Please check out the [scoring theory](https://fusejs.io/concepts/scoring-theory.html) 😄

The list you provided:

```json
[
  {
    "name": "Icon 1c",
    "desc": "Through contributions, donations, and sponsorship, you allow Fuse.js to thrive. Also, you will be recognized as a beacon of support to open-source developers.",
    "notes": "This is only for your reference, it will not display with the component."
  },
  {
    "name": "Icon 3",
    "desc": "The text is used to generate the slug. Note that if you change the slug, the URL of this page will change. Do not change the slug unless really needed."
  }
]
```

Since you didn't specify the [fuzzy-matching options](https://fusejs.io/api/options.html#fuzzy-matching-options), Fuse.js will use the following values:

- `location` defaults to `0`
- `distance` defaults to `100`
- `threshold` defaults to `0.6`

With the above options, for something to be considered a match, it would have to be within (threshold) `0.6` x (distance) `100` = `60` characters away from the expected location `0`. 

But taking each of the search queries (patterns) you provided above:

- `URL` is found at index 77
- `needed` is found at index 144
- `unless` is found at index 130
- `really needed` is found at index 137
- `developers` is found at index 147

Each of those patterns appears more than `60` characters away, therefore they wouldn't match anything. 

If you don't care where the pattern appears in the string, and you still want to consider it a match, set `ignoreLocation` to `true`.

**Comment by krisk** [comment]
@jrista I'd love to also help troubleshoot the issue you highlighted. Do you have a sample list I can use?

**Comment by zehawki** [comment]
Thank you @krisk, `ignoreLocation: true` changes everything. So at least I'm past the first hurdle where I was getting no results at all. Now I have to check for QoR.

--------

But whats the purpose of [location](https://fusejs.io/api/options.html#location)?

And more important why set these default values in particular? (Why would anyone want to search only the 1st 60 chars? Why would anyone want to limit the search in this way?)

In fact, may I suggest that the default should be `ignoreLocation: true`, and then those who need can tailor (reduce) the params accordingly.

**Comment by krisk** [comment]
> And more important why set these default values in particular? (Why would anyone want to search only the 1st 60 chars? Why would anyone want to limit the search in this way?)

Fuse.js was designed with two things in mind: simplicity and search speed. It consequently, by design, does not have sufficiently advanced search capabilities for fields with large text. Internally it uses a modified Bitap algorithm, which is an _approximate string matching_ algorithm, and _tells whether a given text contains a substring that is "approximately equal" to a given pattern, where approximate equality is defined in terms of Levenshtein distance.  if the text and pattern are within a given distance _k_ of each other, then the algorithm considers them equal. [[wiki](https://en.wikipedia.org/wiki/Bitap_algorithm#:~:text=The%20algorithm%20tells%20whether%20a,the%20algorithm%20considers%20them%20equal)]

I would argue that in order to search in large text and have a better relevance score, there are additional algorithms that should be used, such as [td-idf](https://en.wikipedia.org/wiki/Tf%E2%80%93idf). This would produce a "fairer" score relative to the length of text. 

Nonetheless, for those times that users want to search large text, once can always update `location`, `distance` and/or `threshold`. Modifying these, at the very least, still allows for the calculation of the distance. Conversely, simply setting `ignoreLocation` to `true` bypasses the distance location.

**Comment by jrista** [comment]
@krisk At the moment I do not have access to that particular data. This was for a client I had last year. We may pick up with that client again in a few months. I think the data set depicted in the screenshots would probably be sufficient for a test, though...at least the strings from the third column. The `Nur` search, and the fact that it did not seem to accurately match or rank the results was a consistent problem for us (not just with that search). It seemed most searches would either not find the right stuff, or would result in whatever was found being ranked in indecipherable ways...

**Comment by jrista** [comment]
@krisk Any word on how this issue is coming along? May need fuse.js again in an upcoming project, and I'm curious if it is still a viable solution. I think searching text larger than just a couple words or so is a pretty common task for us, and there really are few, if any, other viable search libs for JS. Fuse IS very easy to use, and it would be great if it supported a wider range of string sizes in its search.

**Comment by zehawki** [comment]
> Now I have to check for QoR.

Just wanted to report back on this. Tried with 0.5 threshold for 1 month - was getting irrelevant results. Reduced that to 0.2 for the last 2 months and its been working decently for us so far. Havent seen an issue.

**Comment by leeoniya** [comment]
since this has been marked as `notabug`, [uFuzzy](https://github.com/leeoniya/uFuzzy) might be an alternative to consider.

**Comment by jrista** [comment]
Does anyone know how uFuzzy compares to Fuze when it comes to searching strings longer than a few tens of characters? This is still an issue for us. We seem to often enough, have blocks of text hundreds of chars long, maybe a paragraph or two, that need to be searched.

**Comment by abenhamdine** [comment]
> Does anyone know how uFuzzy compares to Fuze when it comes to searching strings longer than a few tens of characters? This is still an issue for us. We seem to often en

I think you could check that with https://leeoniya.github.io/uFuzzy/demos/compare.html?libs=uFuzzy,fuzzysort,QuickScore,Fuse&search=super%20ma

**Comment by longmauriceproj** [comment]
> Does anyone know how uFuzzy compares to Fuze when it comes to searching strings longer than a few tens of characters? This is still an issue for us. We seem to often enough, have blocks of text hundreds of chars long, maybe a paragraph or two, that need to be searched.

[Flexsearch](https://github.com/nextapps-de/flexsearch) is much better if you want full text search. It's not as straight forward to configure as fuse.

**Comment by leeoniya** [comment]
Flexsearch is good and fast, though if you want fuzzy matching with it you need options that require a huge amount of ram and startup time to build the index.

uFuzzy should perform fine for paragraph-sized haystacks. most of the processing time is spent in the browser's regex engine, which should ve plenty fast for anything that's sub-document-length strings.
