### ISSUE TITLE
Value.trim() is not a function

### ISSUE THREAD

**Issue by sandeepbojan** [krisk/Fuse#583]
I am using the nested object search and I am receiving Value.trim() is not a function error. Could you please help me, why would this error occur

**Comment by dditlev** [comment]
I had the same problem, but I found this small hint in the docs  "The path has to eventually point to a string, otherwise you will not get any results." In the objects (docs) you want to index, you cannot pass values that are not strings, as fuse is trying to trim all the values (removing whitespace from strings). I accidentally passed a doc with a value that was an object. Hope this helps
