### ISSUE TITLE
Typing a number doesn't show the input value at the top

### ISSUE THREAD

**Issue by deadcoder0904** [krisk/Fuse#616]
### Describe the bug
I have a Timezone ComboBox where I use Fuse.js. Timezone has values like `GMT(+05:30) Asia/Kolkata` so when I type `530`, it must naturally show it to the top but it doesn't.

It shows other close values. 

### Version
^6.5.3

### 🔬Minimal Reproduction
https://codesandbox.io/s/combobox-with-fuse-js-t7u4c?file=/src/App.tsx

Relevant code in the `App.tsx` file:

```ts
const options = {
    keys: ["timezone"]
  };

  const fuse = React.useMemo(() => new Fuse(timezonesList, options), []);
  const filteredItems = React.useMemo(
    () => fuse.search(filterValue).map((tz) => tz.item),
    [filterValue, fuse]
  );
```

Try typing `530` & it shows other close values but not the main one.

**Comment by deadcoder0904** [comment]
I went with https://github.com/ajitid/fzf-for-js & it's working for me with a simple setup but still think this is a bug 👍

**Comment by krisk** [comment]
Apologies for the late reply. This is expected behavior given the default settings — `530` doesn't score well against `+05:30` because the characters aren't contiguous (the `+`, `0`, and `:` break up the match). Lowering `threshold` won't help here since it makes matching *stricter*. You'd want to either preprocess the timezone strings to include a digits-only variant (e.g. `"530"` alongside `"+05:30"`), or use `distance: Infinity` with a higher threshold to allow more spread-out matches.
