### ISSUE TITLE
Unintuitive search results

### ISSUE THREAD

**Issue by ChoppinBlockParty** [krisk/Fuse#725]
For the code

```
const fzf = new Fuse<string>(
    [
        'top book options',
        'ice european options'
    ],
    {
        shouldSort: true,
        includeMatches: true,
        includeScore: true,
        ignoreLocation: true
    }
)

fzf.search('ice options')
```

the results would be

```
[
  {
    item: 'top book options',
    refIndex: 0,
    matches: [
      {
        indices: [ [ 0, 3 ], [ 5, 6 ], [ 8, 15 ] ],
        value: 'top book options'
      }
    ],
    score: 0.47251476595266545
  },
  {
    item: 'ice european options',
    refIndex: 1,
    matches: [
      {
        indices: [ [ 0, 4 ], [ 7, 9 ], [ 11, 19 ] ],
        value: 'ice european options'
      }
    ],
    score: 0.47251476595266545
  }
]
```

It is surprising because i would expect the second item to be first in the return list. Any chances to improve the results.

**Comment by krisk** [comment]
This is expected behavior. The Bitap algorithm does character-level fuzzy matching — it treats `"ice options"` as a single 11-character pattern, not two separate words. Both strings have similar edit distances from the pattern, producing identical scores.

If you want word-level matching, use extended search:

```js
const fuse = new Fuse(list, { useExtendedSearch: true });
fuse.search("'ice 'options"); // include-match on both words
```

This correctly ranks `"ice european options"` above `"top book options"` because both words are present.
