### ISSUE TITLE
Threshold seems to be ignored 

### ISSUE THREAD

**Issue by dimitrisfasoulas** [krisk/Fuse#75]
Even though I've set a threshold to 0.6 I seem to get results back with higher scores.

This since the 2.0 update.

**Comment by krisk** [comment]
Ah, this is because version 2 introduced partial matching, that is, approximate string matching is handled in two steps:

1. Search for the pattern in the full entity
2. Search for each token in the pattern (i.e., split by word) in each token of the entity.

Previous versions of Fuse only did the first step, hence the threshold would work as expected. Version 2 and onwards do both step; but in this step the threshold may be considered superfluous, as it really makes no sense. 

Good catch, and woe is me. Need to think of a way to address this.

**Comment by krisk** [comment]
Ok, addressed my making tokenization optional, `false` by default.
