### ISSUE TITLE
All indices return with threshold = 0 aren't a perfect match

### ISSUE THREAD

**Issue by dbismut** [krisk/Fuse#762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

**Version 7.0 (but reproductible in 6.6.2)**

It seems like when using a `threshold` of `0` combined with `ignoreLocation` to return a perfect match, as long as there is one perfect match in the searched text, all other groups of matches are returned no matter how fuzzy they are.

JSFiddle: https://jsfiddle.net/dp4efm2s/12/

### The Fuse.js version where this bug is happening.

7.0.0

### Which version did this behavior use to work in?

Not sure

### Steps To Reproduce

```js
const list = [
{ title: 'rouge desert groue'},
]

const fuseOptions = {
  //isCaseSensitive: false,
  includeScore: true,
  shouldSort: false,
  includeMatches: true,
  findAllMatches: false,
  minMatchCharLength: 2,
  threshold: 0,
  ignoreLocation: true,
  keys: ["title"]
};

const fuse = new Fuse(list, fuseOptions);

// Change the pattern
const searchPattern = "rouge"

console.log(fuse.search(searchPattern))
```

Here is the returned object:

```js
[{
  item: {
    title: "rouge desert groue"
  },
  matches: [{
  indices: [[0, 4], [9, 10], [13, 17]],
  key: "title",
  value: "rouge desert groue"
}],
  refIndex: 0,
  score: 0.01857804455091699
}]
```

### Expected behavior

There is only one perfect matching indice — which is the first one — so only one indice should be returned:

```js
[{
  item: {
    title: "rouge desert groue"
  },
  matches: [{
  indices: [[0, 4]], // only ONE indice should be returned
  key: "title",
  value: "rouge desert groue"
}],
  refIndex: 0,
  score: 0.01857804455091699
}]
```

**Comment by krisk** [comment]
This is a known limitation of how the Bitap algorithm builds its match mask. The mask marks every text position where the character exists in the pattern alphabet, not just positions that are part of the accepted match. So "groue" (an anagram of "rouge") lights up because all its characters appear in the pattern.

The **score** is correct — it reflects the best match found. But the **indices** are noisy because they show character-level alphabet overlaps across the entire scanned range, not just the final match region.

Fixing this would require reworking the match mask logic in the Bitap search, which is a larger effort with potential side effects on highlighting behavior. Noting this for a future pass.
