### ISSUE TITLE
Add plugin functionality

### ISSUE THREAD

**Issue by krisk** [krisk/Fuse#81]
There have been many requests for features and/or enhancements to the library. Some of them are outside the scope or intent of Fuse. Others, however, are in a good position to be included. I'm thinking instead of modifying the core code, we could add extensible pieces to the library - essentially a plugin functionality.

Instead of forcing my vision, I'm interested into what everyone else thinks on how the API should look like.

Tell me your thoughts :smile:

**Comment by Abhinav1217** [comment]
A standard chaining pattern is quite popular in Javascript world, because of Jquery.
```
fuse = new Fuse(arr); 
result = fuse.search(Key).sort("Dec");
```

Or as a PHP developer, I could also prefer something like this.
```
fuse = new Fuse(arr);
fuse.extend(new SortedFuse());
```
or like in PDO based plugins ( I don't think it would suit JS apps. but it is easier to implement ).
```
fuse = new Fuse(arr);
sortfuse = new SortefFuse(fuse);
```

**Comment by shri3k** [comment]
>A standard chaining pattern is quite popular in Javascript world, because of Jquery.

That's all good for core extensibility but not for third party plugins as it will soon cause namespace conflicts. I would like to have something like `pipe` in unix since `fuse` mostly handles the data it would make sense to have `.pipe` (this can be confusing to node's pipe but just an example) or something in that realm.

`.plugin` actually doesn't sound bad but I'm bad with naming so it might actually sound bad for others.
